1669. Merge In Between Linked Lists
1420kartik/Coachable-Kartik-Saini-Repository pull request #2
Opened 2024-12-12 08:55 UTC by 1420kartik

Summary:
We will maintain three pointers: one to track the node where we will insert the new list, the second to track where the new list will point to, and the third to track the tail of the second list so we can point it back to pointer two. Then, we will update the pointers next accordingly to complete the merge.

Let's assume,
len(list1) = m
len(list2) = n
TC: O(m+n)
SC:O(1)

Loom:
https://www.loom.com/share/702afe4299f64ce28791b294e2354679?sid=aa911a62-3ca8-43af-b23612-a80a18434ce1

2024-12-12 23:18 UTC, darekj28 requested changes

2024-12-12 23:18 UTC, darekj28 commented on leetcode/1669_Merge_In_Between_Linked_Lists.py
> +        current_2 = current_1
It's not good practice to combine numbers with variable names. The LC problem did it, so I see why you chose this, but usually you want to avoid this. It's fine for this problem, but let's not make a habit out of this.

2024-12-12 23:18 UTC, darekj28 commented on leetcode/1669_Merge_In_Between_Linked_Lists.py
> +        current_3 = list2
I understand using `current_1, current_2` to track the current node in list1,list2.

However if this is to track the tail, why not call this `tail_2`?

2024-12-18 04:27 UTC, 1420kartik commented
I have made the required changes.

2024-12-20 03:05 UTC, merged