128. Longest Consecutive Sequence
1420kartik/Coachable-Kartik-Saini-Repository pull request #3
Opened 2024-12-12 09:35 UTC by 1420kartik

Summary:
We will convert the nums to set so the look-up time is constant. Then, we will iterate over the nums set to look for consecutive sequences and update the longest streak observed accordingly.
TC: O(n)
SC: O(n)

2024-12-13 01:19 UTC, darekj28 requested changes

2024-12-13 01:19 UTC, darekj28 commented on leetcode/128_Longest_Consecutive_Sequence.py
> +            if number-1 not in nums:
Please add spaces between between operations. 

Specifically `number - 1`

2024-12-13 01:19 UTC, darekj28 commented on leetcode/128_Longest_Consecutive_Sequence.py
> +                while number+1 in nums:
Ditto the comment about operations

2024-12-18 04:33 UTC, 1420kartik commented
I have made the required changes.

2024-12-20 03:06 UTC, merged